spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: user
    password: password
    url: jdbc:mysql://127.0.0.1:3306/table-reservation

logging:
  level:
    root: debug
