spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: user
    password: password
    url: jdbc:mysql://127.0.0.1:3307/table-reservation
  jpa:
    show-sql: true
  logging:
    level:
      root: debug

