CREATE TABLE RESTAURANT (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    category ENUM('TAKE_AWAY', 'DINE_IN', 'BAR', 'CAFE') NOT NULL,
    cuisine ENUM('INDIAN', 'ITALIAN', 'FRENCH', 'FAST_FOOD', 'MISCELLANEOUS') NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE RESTAURANT_TABLE (
    id INT NOT NULL AUTO_INCREMENT,
    restaurant_id INT NOT NULL,
    table_number INT NOT NULL,
    number_of_seats INT NOT NULL,
    type ENUM('HIGHTABLE', 'NORMAL', 'BOOTH') NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_customer FOREIGN KEY (restaurant_id)
    REFERENCES RESTAURANT(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);