CREATE TABLE RESTAURANT (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    category ENUM('TAKE_AWAY', 'DINE_IN', 'BAR', 'CAFE') NOT NULL,
    cuisine ENUM('INDIAN', 'ITALIAN', 'FRENCH', 'FAST_FOOD', 'MISCELLANEOUS') NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id)
);